ResnetAgender:
    onnx_file:     "../weights/R50_agender.onnx"
    engine_file:   "../weights/R50_agender.trt"
    labels_file:   "../configs/labels/Agender.names"
    BATCH_SIZE:    1
    INPUT_CHANNEL: 3
    IMAGE_WIDTH:   288
    IMAGE_HEIGHT:  144
    image_order:   "BCHW"
    channel_order: "BGR"
    img_mean:      [ 0.485, 0.456, 0.406 ]
    img_std:       [ 0.229, 0.224, 0.225 ]
    alpha:         255.0
    resize:        "directly"
