resnet:
    onnx_file:     "../weights/SKY_CLA_COL_blue_20250403.onnx"
    engine_file:   "../weights/SKY_CLA_COL_blue_20250403.trt"
    labels_file:   "../configs/labels/V_colors.names"
    BATCH_SIZE:    1
    INPUT_CHANNEL: 3
    IMAGE_WIDTH:   224
    IMAGE_HEIGHT:  224
    image_order:   "BCHW"
    channel_order: "RGB"
    img_mean:      [ 0.485, 0.456, 0.406 ]
    img_std:       [ 0.229, 0.224, 0.225 ]
    alpha:         255.0
    resize:        "directly"
